# Generated by Django 3.2.14 on 2022-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='duracion',
            field=models.CharField(default='1 hora', max_length=15),
        ),
    ]
